### ISSUE TITLE
Enable `dev deploy` for the CPG instance

### ISSUE THREAD

**Issue by lgruen** [populationgenomics/hail#19]
We'll need to deploy the `ci` service, but also remove any watched GitHub branches (we don't want to deploy whenever we push to `main`).

**Comment by lgruen** [comment]
We probably don't need a GitHub OAuth token and Zulip configs in `ci/deployment.yaml`, but the SQL config seems to be necessary:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/ci/__main__.py", line 8, in <module>
    run()
  File "/usr/local/lib/python3.7/dist-packages/ci/ci.py", line 439, in run
    ssl_context=internal_server_ssl_context(),
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web.py", line 433, in run_app
    reuse_port=reuse_port))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web.py", line 305, in _run_app
    await runner.setup()
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web_runner.py", line 232, in setup
    self._server = await self._make_server()
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web_runner.py", line 331, in _make_server
    await self._app.startup()
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web_app.py", line 389, in startup
    await self.on_startup.send(self)
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/signals.py", line 34, in send
    await receiver(*args, **kwargs)  # type: ignore
  File "/usr/local/lib/python3.7/dist-packages/ci/ci.py", line 406, in on_startup
    app['dbpool'] = await create_database_pool()
  File "/usr/local/lib/python3.7/dist-packages/gear/database.py", line 29, in wrapper
    return await f(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gear/database.py", line 91, in create_database_pool
    sql_config = get_sql_config(config_file)
  File "/usr/local/lib/python3.7/dist-packages/gear/database.py", line 64, in get_sql_config
    with open(config_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/sql-config/sql-config.json'
```

**Comment by lgruen** [comment]
The SQL database doesn't seem to be required, but running into some permission errors now:

```
    "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/dist-packages/batch/driver/job.py\", line 350, in schedule_job\n    body = await job_config(app, record, attempt_id)\n  File \"/usr/local/lib/python3.7/dist-packages/batch/driver/job.py\", line 270, in job_config\n    name, namespace, KUBERNETES_TIMEOUT_IN_SECONDS)\n  File \"/usr/local/lib/python3.7/dist-packages/batch/driver/k8s_cache.py\", line 74, in read_service_account\n    _request_timeout=timeout)\n  File \"/usr/local/lib/python3.7/dist-packages/hailtop/utils/utils.py\", line 390, in retry_transient_errors\n    return await f(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/dist-packages/kubernetes_asyncio/client/api_client.py\", line 166, in __call_api\n    _request_timeout=_request_timeout)\n  File \"/usr/local/lib/python3.7/dist-packages/kubernetes_asyncio/client/rest.py\", line 191, in GET\n    query_params=query_params))\n  File \"/usr/local/lib/python3.7/dist-packages/kubernetes_asyncio/client/rest.py\", line 181, in request\n    raise ApiException(http_resp=r)\nkubernetes_asyncio.client.rest.ApiException: (403)\nReason: Forbidden\nHTTP response headers: <CIMultiDictProxy('Audit-Id': '773434b6-3961-4092-8587-cd1e10654424', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Thu, 04 Feb 2021 23:23:48 GMT', 'Content-Length': '350')>\nHTTP response body: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"serviceaccounts \\\"admin\\\" is forbidden: User \\\"system:serviceaccount:default:batch\\\" cannot get resource \\\"serviceaccounts\\\" in API group \\\"\\\" in the namespace \\\"leonhardgruenschloss\\\"\",\"reason\":\"Forbidden\",\"details\":{\"name\":\"admin\",\"kind\":\"serviceaccounts\"},\"code\":403}\n\n\n",
```
